### ISSUE TITLE
New dialog for testing and aligning hardware

### ISSUE THREAD

**Issue by mariolukas** [mariolukas/FabScanPi-Server#100]
The dialog should have different tabs:

- Hardware controls
- Calibration 
- Info/System
- Help/support (later)
- wifi/network config

**wifi/network config**
- settings for netconnecd 

**Hardware Tab**
This Tab should be generic, for different kinds of implemented interfaces.
- turn on/off lasers
- turn on/off stepper motor
- camera preview

**Calibration Tab**
- calibration settings /edit
- start calibration 
- show current calibration values

**System  Tab**
- show firmware and server version
- check for updates 
- shutdown
- reboot

added last two points, suggested by @CONSULitAS

**Comment by CONSULitAS** [comment]
how about
* shutdown
* reboot

**Comment by mariolukas** [comment]
Thank you for this suggestion, i forget to add this. Backend is already prepared for that.
