### ISSUE TITLE
[not an issue] Is this project still under active development / support?

### ISSUE THREAD

**Issue by careyer** [mariolukas/FabScanPi-Server#121]

**Comment by mariolukas** [comment]
Yes it is. I am more active in the dev branch at the moment.
https://github.com/mariolukas/FabScanPi-Server/tree/dev

There are more recent testing versions in the testing branch
of the package repository. 

Best way for getting support is slack. 
http://mariolukas.github.io/FabScanPi-Server/community/

**Comment by careyer** [comment]
Ahhh!!! Great! Thanks... I did not notice that there was recent activity other than in the master branch. I was just curious because the latest release was kind of old already (26 Jul 2017).  Keep up the excellent work!

**Comment by mariolukas** [comment]
v.0.5.0 is out.
