### ISSUE TITLE
Power consumption Raspberry Pi 3 Model B+ and FabScanPI HAT

### ISSUE THREAD

**Issue by mariolukas** [mariolukas/FabScanPi-Server#122]
## *Who* is the bug affecting?
Users of the new Raspberry Pi 3 Model B+

## *What* is affected by this bug?
Raspberry Pi 3 Model B+ has a higher power consumption, 
so that the FabScanPi HAT with stepdown will not serve 
enough power. 

## *Where* on the platform does it happen?
FabScanPi HAT.

## Expected behavior (i.e. solution)
People using the Raspberry Pi 3 Model B+ should not solder the stepdown and use
two different (12v supply for HAT and 5V Supply for Pi) port supplies.

Add this to the documentation until we have a hardware fix for it.

**Comment by thatSFguy** [comment]
What are the symptoms of not having enough power?  I'm having problems with hung scans, frozen PIcamera, etc.  so I was wondering if this could be a problem for me.  I'm using a DIY board, but probably very similar to your HAT implementation.  Thanks!

**Comment by mariolukas** [comment]
The CPU slow down, sometimes freezes. There are different symptoms with under voltage. The pi is not able to work as expected.
