### ISSUE TITLE
Feature Request - Atlas/Ciclop compatibility

### ISSUE THREAD

**Issue by wer-is-paul** [mariolukas/FabScanPi-Server#123]
Hi,

I'm trying to implement this but I'm getting stucked on camera ready log. I can remote debug using pycharm. Anyone else working on this?

Cheers, 

Dominik

**Comment by mariolukas** [comment]
Hey I am just working on supporting Atlas/Ciclop scanners. I already added USB Cam support in version 0.5.0 and i am making the firmware compatible right now.
Do you have a PyCharm Pro version? The CE Edition does not support remote debugging.

**Comment by wer-is-paul** [comment]
Hi,

Yes, it's the pro version. But good to know. Is there a roadmap for the next version yet?

Cheers,

Dominik

**Comment by mariolukas** [comment]
USB Cam Driver starts here 
https://github.com/mariolukas/FabScanPiServer/blob/master/src/fabscan/scanner/laserscanner/FSCamera.py#L288
It should work already. Just add USBCAM as camera type to the config. 
I will try to add a short remote debug tutorial to the docs this weekend.

**Comment by mariolukas** [comment]
The ciclop support will be within the next release. But not working with the usb cam. You need to mount a raspberry pi cam on the ciclop Support for the atlas scanner will follow later, cause the atlas scanner uses a different electronics approach ( pi GPIO ). 
I added some pictures of the ciclop setup to the [forum](https://fabscan.org/community/development/second-laser-when/).
