### ISSUE TITLE
WebUI doesn't shows scan progres if no Internet

### ISSUE THREAD

**Issue by iadegesso** [mariolukas/FabScanPi-Server#131]
Hi,
when I use the FabScan in an isolated LAN, no scan progress is shown in the web-based UI...

Please statically include all the libraries in the package.

Version 0.7.0

**Comment by mariolukas** [comment]
Thank you for reporting. It is a known issue. I will fix that within the next release.

**Comment by iadegesso** [comment]
Mario,
can you provide us an idea about the time of the next release?

Iade

**Comment by mariolukas** [comment]
At the moment I am doing final tests on it. I think I will do a release within the next two weeks.

**Comment by mariolukas** [comment]
This is fixed within 0.9.4.
