### ISSUE TITLE
Changelog???

### ISSUE THREAD

**Issue by Azubiwork** [mariolukas/FabScanPi-Server#143]
Seems there's a new version of the image available.

BUT: I Cannot find any changelog that's up-to-date. Or a list of known bugs for the update...

**Comment by mariolukas** [comment]
The image update only belongs to operating system related updates. 
https://github.com/mariolukas/FabScanPi-Build-Raspbian/releases/tag/v.2020-05-27-00-08
You can find the changes in the release info. 

- fixes Raspbian opencv update issue
- brings newest raspbian packages

So this does not belong to the server software. But the new image also allows you to use the testing branch for testing the upcoming release without problems.
