### ISSUE TITLE
Add documentation PI HAT Connection 

### ISSUE THREAD

**Issue by mariolukas** [mariolukas/FabScanPi-Server#38]
- power jack polarity
- wireing diagram 
- laser secure switch (bridge)
- jst connector polartity (howto connect led stripe/ring)
- silent step stick driver configuration/assembly
- howto test connectivity
- troubleshooting section

**Comment by jenshackel** [comment]
This will be my next "construction site".

**Comment by Cysign** [comment]
- Add info about voltage/maximum current for the laser connectors

- Add instructions to setup the stepper current properly

- Add checklist 'before you turn on your machine'

**Comment by Cysign** [comment]
- Add information if a resistor for an DIY-WS2812 strip is needed on the signal

- Does the Hat deliver power to the Pi?

- Add: Use some tape on audiojack & hdmi port to properly isolate hat from Pi !

**Comment by mariolukas** [comment]
Thank you for your suggestions, we will add those points to the hardware related docs.
