### ISSUE TITLE
missing ng.jsoneditor (Error: $injector:modulerr Module Error) and logo.png

### ISSUE THREAD

**Issue by brummbaer** [mariolukas/FabScanPi-Server#59]
Failed to instantiate module fabscan: [ng.jsoneditor](https://docs.angularjs.org/error/$injector/modulerr?p0=fabscan&p1=%5B$injector:modulerr%5D%20Failed%20to%20instantiate%20module%20ng.jsoneditor%20due%20to:%0A%5B$injector:nomod%5D%20Module%20'ng.jsoneditor'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp:%2F%2Ferrors.angularjs.org%2F1.2.26%2F$injector%2Fnomod%3Fp0%3Dng.jsoneditor%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:948%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:8848%0At@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:8431%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:8743%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:16043%0Ao@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:1284%0Ah@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:15982%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:16059%0Ao@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:1284%0Ah@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:15982%0APt@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:17534%0Aa@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:7084%0AJ@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:7295%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Fapp.js:1:1251%0Au@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:2:5803%0AfireWith@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:2:6617%0Aready@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:2:8475%0As@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:1:1147%0Ahttp:%2F%2Ferrors.angularjs.org%2F1.2.26%2F$injector%2Fmodulerr%3Fp0%3Dng.jsoneditor%26p1%3D%255B%2524injector%253Anomod%255D%2520Module%2520'ng.jsoneditor'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.2.26%252F%2524injector%252Fnomod%253Fp0%253Dng.jsoneditor%250Ahttp%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A948%250Ahttp%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A8848%250At%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A8431%250Ahttp%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A8743%250Ahttp%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A16043%250Ao%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A1284%250Ah%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A15982%250Ahttp%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A16059%250Ao%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A1284%250Ah%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A15982%250APt%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A17534%250Aa%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A7084%250AJ%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A4%253A7295%250Ahttp%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Fapp.js%253A1%253A1251%250Au%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A2%253A5803%250AfireWith%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A2%253A6617%250Aready%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A2%253A8475%250As%2540http%253A%252F%252F192.168.2.172%253A8080%252Fjs%252Flib.js%253A1%253A1147%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:948%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:16374%0Ao@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:1284%0Ah@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:15982%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:16059%0Ao@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:1284%0Ah@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:15982%0APt@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:17534%0Aa@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:7084%0AJ@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:4:7295%0Ahttp:%2F%2F192.168.2.172:8080%2Fjs%2Fapp.js:1:1251%0Au@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:2:5803%0AfireWith@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:2:6617%0Aready@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:2:8475%0As@http:%2F%2F192.168.2.172:8080%2Fjs%2Flib.js:1:1147) 
and missing logo.png in icons.
Resulting in a blank browser page.

**Comment by mariolukas** [comment]
Thank you for the hint, i just added the missing parts.
