### ISSUE TITLE
Job for fabscanpi-server.service failed on pi.

### ISSUE THREAD

**Issue by brummbaer** [mariolukas/FabScanPi-Server#64]
Add a hashpling to the beginning of /etc/init.d/fabscanpi-server.
# !/bin/bash

...

**Comment by mariolukas** [comment]
[ As Reminder] Related to this file: 
https://github.com/mariolukas/FabScanPi-Server/blob/master/debian/fabscanpi-server.init

**Comment by mariolukas** [comment]
solved
